export const stars = [
    'Ashwini',
    'Bharani',
    'Kritthika',
    'Rohini',
    'Mrgashirsha',
    'Ardhra',
    'Punarvasu',
    'Pushya',
    'Ashlesha',
    'Magha',
    'Poorva Phalguni',
    'Uthara Phalguni',
    'Hastham',
    'Chithra',
    'Swathi',
    'Vaishaka',
    'Anuradha',
    'Jyeshta',
    'Moola',
    'Poorva Ashada',
    'Uthara Ashada',
    'Shravana',
    'Dhanishta',
    'Shathabisha',
    'Poorva Bhadrapada',
    'Uthara Bhadrapada',
    'Revathi'
];
